#Practica 4

#Ejercicio 1.
censo<-read.csv('census.csv',header=TRUE,as.is=NA)
getwd()
lapply(censo,class)
help(read.csv)
lapply(censo,is.na)
lapply(lapply(censo,is.na),sum)
typeof(complete.cases(censo))
sum(complete.cases(censo))
censo2<-censo[complete.cases(censo),]
censo2<-na.omit(censo)
write.table(censo2,file='censo2.txt',row.names=FALSE,sep='\t')
help(write.table)
censo3 <- read.table("censo2.txt", header = TRUE, as.is = NA)
str(censo3)
str(censo2)
#Ejercicio 2.
nomb<-paste0('col',1:5)
matriz<-matrix(rnorm(50),10,5,dimnames=list(NULL,nomb))
matriz
write(nomb,file='matriz.txt',ncol=5,sep=',')
write(t(matriz),file='matriz.txt',ncol=5,sep=',',append=TRUE)
matriz2<-read.csv('matriz.txt',header=TRUE)
str(matriz2)
olympics <- read.csv("Olympics100m.csv", header = TRUE, as.is = c(2))
lapply(olympics,class)
lapply(lapply(olympics,is.na),sum)
resumen<-summary(olympics)
is.matrix(resumen)
typeof(resumen)
class(resumen)
write.table(resumen, file = "resumen.txt", row.names = FALSE)
resumen.leido <- read.table("resumen.txt")
resumen2<-aggregate(olympics$TIME,by=list(olympics$Gender),summary)
write.table(resumen2, file = "resumen2.txt", sep = ",", row.names = FALSE)
resumen2.leido <- read.csv(file = "resumen2.txt", header = T)
str(resumen2.leido)
